<?php

declare(strict_types=1);

use Prism\Prism\Providers\OpenRouter\Maps\ToolMap;
use Prism\Prism\Tool;

it('maps tools', function (): void {
    $tool = (new Tool)
        ->as('search')
        ->for('Searching the web')
        ->withStringParameter('query', 'the detailed search query')
        ->using(fn (): string => '[Search results]');

    expect(ToolMap::map([$tool]))->toEqual([[
        'type' => 'function',
        'function' => [
            'name' => $tool->name(),
            'description' => $tool->description(),
            'parameters' => [
                'type' => 'object',
                'properties' => (object) [
                    'query' => (object) [
                        'description' => 'the detailed search query',
                        'type' => 'string',
                    ],
                ],
                'required' => $tool->requiredParameters(),
            ],
        ],
    ]]);
});

it('generates parameters only once from conditional spread', function (): void {
    $withParams = (new Tool)
        ->as('search')
        ->for('Search the web')
        ->withStringParameter('query', 'the search query')
        ->withNumberParameter('limit', 'max results', required: false)
        ->using(fn (): string => '[results]');

    $withoutParams = (new Tool)
        ->as('get_time')
        ->for('Returns the current time')
        ->using(fn (): string => now()->toISOString());

    $mapped = ToolMap::map([$withParams, $withoutParams]);

    // Tool WITH parameters: parameters is generated once by the conditional spread
    $searchFn = $mapped[0]['function'];
    expect($searchFn)->toHaveKey('parameters');
    expect($searchFn['parameters'])->toEqual([
        'type' => 'object',
        'properties' => (object) [
            'query' => (object) [
                'description' => 'the search query',
                'type' => 'string',
            ],
            'limit' => (object) [
                'description' => 'max results',
                'type' => 'number',
            ],
        ],
        'required' => ['query'],
    ]);

    // Tool WITHOUT parameters: conditional spread adds nothing,
    // and no static duplicate exists to add it back
    $timeFn = $mapped[1]['function'];
    expect($timeFn)->not->toHaveKey('parameters');
    expect(array_keys($timeFn))->toEqual(['name', 'description']);
});

it('proves parameters is generated by conditional spread not static duplicate', function (): void {
    // Mock a tool where hasParameters()=true but parametersAsArray()=[]
    // KEY 1 (conditional spread) produces: 'properties' => new \stdClass (JSON: {})
    // KEY 2 (static duplicate)   produces: 'properties' => (object) []            (JSON: [])
    // If KEY 2 overwrites KEY 1, properties will be [] not stdClass

    $tool = Mockery::mock(Tool::class);
    $tool->shouldReceive('name')->andReturn('mock_tool');
    $tool->shouldReceive('description')->andReturn('A mock tool');
    $tool->shouldReceive('hasParameters')->andReturn(true);
    $tool->shouldReceive('parametersAsObject')->andReturn(new stdClass);
    $tool->shouldReceive('requiredParameters')->andReturn([]);
    $tool->shouldReceive('providerOptions')->with('strict')->andReturn(null);

    $mapped = ToolMap::map([$tool]);
    $properties = $mapped[0]['function']['parameters']['properties'];

    // KEY 1 wraps empty properties in stdClass (serializes as JSON {})
    // KEY 2 would leave it as [] (serializes as JSON [])
    // If this is stdClass, KEY 1 produced it. If array, KEY 2 overwrote it.
    expect($properties)->toBeInstanceOf(stdClass::class, 'parameters.properties should be stdClass from conditional spread, not [] from static duplicate');
});

it('maps tools with strict mode', function (): void {
    $tool = (new Tool)
        ->as('search')
        ->for('Searching the web')
        ->withStringParameter('query', 'the detailed search query')
        ->using(fn (): string => '[Search results]')
        ->withProviderOptions([
            'strict' => true,
        ]);

    expect(ToolMap::map([$tool]))->toEqual([[
        'type' => 'function',
        'function' => [
            'name' => $tool->name(),
            'description' => $tool->description(),
            'parameters' => [
                'type' => 'object',
                'properties' => (object) [
                    'query' => (object) [
                        'description' => 'the detailed search query',
                        'type' => 'string',
                    ],
                ],
                'required' => $tool->requiredParameters(),
            ],
        ],
        'strict' => true,
    ]]);
});
